samples:
  Blank-1 :
    - ../data/raw_reads/A1_R1.fastq.gz
    - ../data/raw_reads/A1_R2.fastq.gz
  820-A-1 :
    - ../data/raw_reads/B1_R1.fastq.gz
    - ../data/raw_reads/B1_R2.fastq.gz
  822-none-1 :
    - ../data/raw_reads/C1_R1.fastq.gz
    - ../data/raw_reads/C1_R2.fastq.gz
  198-none-1 :
    - ../data/raw_reads/D1_R1.fastq.gz
    - ../data/raw_reads/D1_R2.fastq.gz
  199-none-1 :
    - ../data/raw_reads/E1_R1.fastq.gz
    - ../data/raw_reads/E1_R2.fastq.gz
  200-none-1 :
    - ../data/raw_reads/F1_R1.fastq.gz
    - ../data/raw_reads/F1_R2.fastq.gz
  819-none-1 :
    - ../data/raw_reads/G1_R1.fastq.gz
    - ../data/raw_reads/G1_R2.fastq.gz
  824-A-1 :
    - ../data/raw_reads/H1_R1.fastq.gz
    - ../data/raw_reads/H1_R2.fastq.gz
  827-C-1 :
    - ../data/raw_reads/A2_R1.fastq.gz
    - ../data/raw_reads/A2_R2.fastq.gz
  1060-C-1 :
    - ../data/raw_reads/B2_R1.fastq.gz
    - ../data/raw_reads/B2_R2.fastq.gz
  1069-none-1 :
    - ../data/raw_reads/C2_R1.fastq.gz
    - ../data/raw_reads/C2_R2.fastq.gz
  1077-C-1 :
    - ../data/raw_reads/D2_R1.fastq.gz
    - ../data/raw_reads/D2_R2.fastq.gz
  170-B-1 :
    - ../data/raw_reads/E2_R1.fastq.gz
    - ../data/raw_reads/E2_R2.fastq.gz
  mixSW-A-1 :
    - ../data/raw_reads/F2_R1.fastq.gz
    - ../data/raw_reads/F2_R2.fastq.gz
  mixPE-C-1 :
    - ../data/raw_reads/G2_R1.fastq.gz
    - ../data/raw_reads/G2_R2.fastq.gz
  Blank-2 :
    - ../data/raw_reads/H2_R1.fastq.gz
    - ../data/raw_reads/H2_R2.fastq.gz
  820-none-2 :
    - ../data/raw_reads/A3_R1.fastq.gz
    - ../data/raw_reads/A3_R2.fastq.gz
  822-C-2 :
    - ../data/raw_reads/B3_R1.fastq.gz
    - ../data/raw_reads/B3_R2.fastq.gz
  198-A-2 :
    - ../data/raw_reads/C3_R1.fastq.gz
    - ../data/raw_reads/C3_R2.fastq.gz
  199-A-2 :
    - ../data/raw_reads/D3_R1.fastq.gz
    - ../data/raw_reads/D3_R2.fastq.gz
  200-B-2 :
    - ../data/raw_reads/E3_R1.fastq.gz
    - ../data/raw_reads/E3_R2.fastq.gz
  819-B-2 :
    - ../data/raw_reads/F3_R1.fastq.gz
    - ../data/raw_reads/F3_R2.fastq.gz
  824-B-2 :
    - ../data/raw_reads/G3_R1.fastq.gz
    - ../data/raw_reads/G3_R2.fastq.gz
  827-A-2 :
    - ../data/raw_reads/H3_R1.fastq.gz
    - ../data/raw_reads/H3_R2.fastq.gz
  1060-B-2 :
    - ../data/raw_reads/A4_R1.fastq.gz
    - ../data/raw_reads/A4_R2.fastq.gz
  1069-B-2 :
    - ../data/raw_reads/B4_R1.fastq.gz
    - ../data/raw_reads/B4_R2.fastq.gz
  1077-A-2 :
    - ../data/raw_reads/C4_R1.fastq.gz
    - ../data/raw_reads/C4_R2.fastq.gz
  170-none-2 :
    - ../data/raw_reads/D4_R1.fastq.gz
    - ../data/raw_reads/D4_R2.fastq.gz
  mixSW-C-2 :
    - ../data/raw_reads/E4_R1.fastq.gz
    - ../data/raw_reads/E4_R2.fastq.gz
  mixPE-B-2 :
    - ../data/raw_reads/F4_R1.fastq.gz
    - ../data/raw_reads/F4_R2.fastq.gz
  Blank-3 :
    - ../data/raw_reads/G4_R1.fastq.gz
    - ../data/raw_reads/G4_R2.fastq.gz
  820-C-3 :
    - ../data/raw_reads/H4_R1.fastq.gz
    - ../data/raw_reads/H4_R2.fastq.gz
  822-B-3 :
    - ../data/raw_reads/A5_R1.fastq.gz
    - ../data/raw_reads/A5_R2.fastq.gz
  198-B-5 :
    - ../data/raw_reads/B5_R1.fastq.gz
    - ../data/raw_reads/B5_R2.fastq.gz
  199-C-3 :
    - ../data/raw_reads/C5_R1.fastq.gz
    - ../data/raw_reads/C5_R2.fastq.gz
  200-C-3 :
    - ../data/raw_reads/D5_R1.fastq.gz
    - ../data/raw_reads/D5_R2.fastq.gz
  819-A-3 :
    - ../data/raw_reads/E5_R1.fastq.gz
    - ../data/raw_reads/E5_R2.fastq.gz
  824-none-3 :
    - ../data/raw_reads/F5_R1.fastq.gz
    - ../data/raw_reads/F5_R2.fastq.gz
  827-none-3 :
    - ../data/raw_reads/G5_R1.fastq.gz
    - ../data/raw_reads/G5_R2.fastq.gz
  1060-none-3 :
    - ../data/raw_reads/H5_R1.fastq.gz
    - ../data/raw_reads/H5_R2.fastq.gz
  1069-C-3 :
    - ../data/raw_reads/A6_R1.fastq.gz
    - ../data/raw_reads/A6_R2.fastq.gz
  1077-B-3 :
    - ../data/raw_reads/B6_R1.fastq.gz
    - ../data/raw_reads/B6_R2.fastq.gz
  170-A-3 :
    - ../data/raw_reads/C6_R1.fastq.gz
    - ../data/raw_reads/C6_R2.fastq.gz
  mixSW-none-3 :
    - ../data/raw_reads/D6_R1.fastq.gz
    - ../data/raw_reads/D6_R2.fastq.gz
  mixPE-A-3 :
    - ../data/raw_reads/E6_R1.fastq.gz
    - ../data/raw_reads/E6_R2.fastq.gz
  Pc-A-5 :
    - ../data/raw_reads/F6_R1.fastq.gz
    - ../data/raw_reads/F6_R2.fastq.gz
  Pc-B-5 :
    - ../data/raw_reads/G6_R1.fastq.gz
    - ../data/raw_reads/G6_R2.fastq.gz
  Pc-C-5 :
    - ../data/raw_reads/H6_R1.fastq.gz
    - ../data/raw_reads/H6_R2.fastq.gz
  Blank-4 :
    - ../data/raw_reads/A7_R1.fastq.gz
    - ../data/raw_reads/A7_R2.fastq.gz
  820-B-4 :
    - ../data/raw_reads/B7_R1.fastq.gz
    - ../data/raw_reads/B7_R2.fastq.gz
  822-A-4 :
    - ../data/raw_reads/C7_R1.fastq.gz
    - ../data/raw_reads/C7_R2.fastq.gz
  198-C-4 :
    - ../data/raw_reads/D7_R1.fastq.gz
    - ../data/raw_reads/D7_R2.fastq.gz
  199-B-4 :
    - ../data/raw_reads/E7_R1.fastq.gz
    - ../data/raw_reads/E7_R2.fastq.gz
  200-A-4 :
    - ../data/raw_reads/F7_R1.fastq.gz
    - ../data/raw_reads/F7_R2.fastq.gz
  819-C-4 :
    - ../data/raw_reads/G7_R1.fastq.gz
    - ../data/raw_reads/G7_R2.fastq.gz
  824-C-4 :
    - ../data/raw_reads/H7_R1.fastq.gz
    - ../data/raw_reads/H7_R2.fastq.gz
  827-B-4 :
    - ../data/raw_reads/A8_R1.fastq.gz
    - ../data/raw_reads/A8_R2.fastq.gz
  1060-A-4 :
    - ../data/raw_reads/B8_R1.fastq.gz
    - ../data/raw_reads/B8_R2.fastq.gz
  1069-A-4 :
    - ../data/raw_reads/C8_R1.fastq.gz
    - ../data/raw_reads/C8_R2.fastq.gz
  1077-none-4 :
    - ../data/raw_reads/D8_R1.fastq.gz
    - ../data/raw_reads/D8_R2.fastq.gz
  170-C-4 :
    - ../data/raw_reads/E8_R1.fastq.gz
    - ../data/raw_reads/E8_R2.fastq.gz
  mixSW-B-4 :
    - ../data/raw_reads/F8_R1.fastq.gz
    - ../data/raw_reads/F8_R2.fastq.gz
  mixPE-none-4 :
    - ../data/raw_reads/G8_R1.fastq.gz
    - ../data/raw_reads/G8_R2.fastq.gz

BiCom:
  ESL0170:
    - ../data/references/Bifido_genomes/ESL0170.fasta
  ESL1077:
    - ../data/references/Bifido_genomes/ESL1077.fasta
  ESL1060:
    - ../data/references/Bifido_genomes/ESL1060.fasta
  ESL1069:
    - ../data/references/Bifido_genomes/ESL1069.fasta
  ESL0819:
    - ../data/references/Bifido_genomes/ESL0819.fasta
  ESL0820:
    - ../data/references/Bifido_genomes/ESL0820.fasta
  ESL0822:
    - ../data/references/Bifido_genomes/ESL0822.fasta
  ESL0824:
    - ../data/references/Bifido_genomes/ESL0824.fasta
  ESL0827:
    - ../data/references/Bifido_genomes/ESL0827.fasta
  ESL0198:
    - ../data/references/Bifido_genomes/ESL0198.fasta
  ESL0199:
    - ../data/references/Bifido_genomes/ESL0199.fasta
  ESL0200:
    - ../data/references/Bifido_genomes/ESL0200.fasta

all_bifidos:
  - BAST
  - BCOR
  - BINDI
  - ESL0170
  - ESL0198
  - ESL0199
  - ESL0200
  - ESL0819
  - ESL0820
  - ESL0822
  - ESL0824
  - ESL0825
  - ESL0827
  - ESL1057
  - ESL1058
  - ESL1059
  - ESL1060
  - ESL1062
  - ESL1063
  - ESL1065
  - ESL1066
  - ESL1069
  - ESL1070
  - ESL1071
  - ESL1072
  - ESL1073
  - ESL1076
  - ESL1077
  - ESL1078
  - ESL1080
  - ESL1081
  - ESL1083
  - ESL1086
  - ESL1087
  - ESL1088
  - ESL1090
  - Ga0056940
  - Ga0057557
  - Ga0070887
  - Ga0070888
  - Ga0072395
  - Ga0072396
  - Ga0072398
  - Ga0072399
  - Ga0072401
  - Ga0098206
  - Ga0133549
  - Ga0133550
  - Ga0133551
  - Ga0133553
  - Ga0133561
  - Ga0133563
  - Ga0226840
  - Ga0312305
  - H3S92
  - H3S93
  - H3S97
  - H3T81
  - H3T86
  - H3T89
  - H3T90
  - H3T91
  - H3T92
  - H3T93
  - H3U87
  - H3U88
  - H3U89
  - H3U98
  - H3V04
  - H3V06
  - H3V08
  
DRAM_CONFIG: ../config/dram_config.json
DF_MODELS: ../resources/databases/DefenseFinder_models
CHECKV_DB: /work/FAC/FBM/DMF/pengel/default/mndiaye1/checkv-db-v1.5
PHABOX_DB: /work/FAC/FBM/DMF/pengel/general_data/mndiaye1/databases/phabox_db_v2